version: "3"

services:
  ollama:
#    image: mrizwank97/medgpt_ollama:${IMAGE_TAG}
    image: mrizwank97/medgpt_ollama:${IMAGE_TAG}
    ports:
      - 11434:11434
    volumes:
       - ./ollama:/ollama
    entrypoint: ["/usr/bin/bash", "/start_ollama.sh"]

  web:
    image: mrizwank97/medgpt_api:${IMAGE_TAG}
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    depends_on:
      - ollama