version: "3"

services:
  web:
    build: fastapi
    ports:
      - 8000:8000
    volumes:
      - ./fastapi:/app
  ollama:
    build: ollama
    ports:
      - 11434:11434
    volumes:
      - ./ollama:/ollama
    entrypoint: ["/usr/bin/bash", "/start_ollama.sh"]